"""One-round reflow training on precomputed ``(x_0, z_1)`` pairs.

This module reuses the standard conditional flow architecture, but it swaps the
Stage-1 target density with a saved reflow endpoint generated by an earlier
flow model. Each training sample therefore supplies:

- ``data``: the conditioning density (SAD guess);
- ``label``: the original ground-truth density, kept for evaluation;
- ``source``: the fixed source state ``x_0`` used during reflow generation;
- ``reflow_target``: the ODE endpoint ``z_1`` generated from that source.
"""

from __future__ import annotations

import torch

from electrai.lightning_flow import LightningFlowMatch


class LightningFlowMatchReflow(LightningFlowMatch):
    """Retrain the flow on one round of precomputed reflow pairs."""

    def __init__(self, cfg):
        super().__init__(cfg)
        self.reflow_endpoint_target = str(
            getattr(cfg, 'reflow_endpoint_target', 'data'),
        ).lower()
        if self.reflow_endpoint_target not in {'data', 'reflow'}:
            raise ValueError(
                'reflow_endpoint_target must be either '
                f"'data' or 'reflow', got {self.reflow_endpoint_target!r}.",
            )

    def _iter_reflow_batch_samples(self, batch):
        cond = batch['data']
        x_1 = batch['label']
        source = batch.get('source')
        reflow_target = batch.get('reflow_target')
        indices = batch.get('index')

        if source is None or reflow_target is None:
            raise KeyError(
                "Reflow batches must include 'source' and 'reflow_target' keys.",
            )

        if isinstance(cond, list):
            if indices is None:
                indices = [None] * len(cond)
            for cond_i, target_i, source_i, reflow_i, index_i in zip(
                cond, x_1, source, reflow_target, indices, strict=True,
            ):
                if cond_i.ndim == 4:
                    cond_i = cond_i.unsqueeze(0)
                if target_i.ndim == 4:
                    target_i = target_i.unsqueeze(0)
                if source_i.ndim == 4:
                    source_i = source_i.unsqueeze(0)
                if reflow_i.ndim == 4:
                    reflow_i = reflow_i.unsqueeze(0)
                yield cond_i, target_i, source_i, reflow_i, index_i
            return

        yield cond, x_1, source, reflow_target, indices

    def _objective_terms_reflow(
        self,
        cond: torch.Tensor,
        x_1: torch.Tensor,
        source: torch.Tensor,
        reflow_target: torch.Tensor,
        *,
        stage: str,
    ) -> dict[str, torch.Tensor]:
        bsz = x_1.shape[0]
        device = x_1.device

        model_cond = self._condition_for_model(cond, stage=stage)
        x_0 = source.to(device=device, dtype=reflow_target.dtype)
        target_state = reflow_target.to(device=device, dtype=x_1.dtype)
        t = torch.rand(bsz, device=device) * (1.0 - self.eps) + self.eps
        t_expand = t.view(bsz, 1, 1, 1, 1)
        z_t = t_expand * target_state + (1.0 - t_expand) * x_0
        target = target_state - x_0

        model_input = torch.cat([z_t, model_cond], dim=1)
        v_pred = self.model(model_input, t)

        flow_mse = ((v_pred - target) ** 2).mean()
        state_hat = z_t + (1.0 - t_expand) * v_pred
        x_1_hat = self._prediction_from_state(state_hat, cond)

        endpoint_target = reflow_target
        if self.reflow_endpoint_target == 'data':
            endpoint_target = x_1

        endpoint_nmae = self.nmae_loss(x_1_hat, endpoint_target)
        endpoint_mass = self.mass_loss(x_1_hat, endpoint_target)

        loss = (
            self.flow_loss_weight * flow_mse
            + self.endpoint_nmae_weight * endpoint_nmae
            + self.endpoint_mass_weight * endpoint_mass
        )
        return {
            'loss': loss,
            'flow_mse': flow_mse,
            'endpoint_nmae': endpoint_nmae,
            'endpoint_mass': endpoint_mass,
        }

    def _objective_from_batch(self, batch, *, stage: str):
        metrics = [
            self._objective_terms_reflow(
                cond,
                target,
                source,
                reflow_target,
                stage=stage,
            )
            for cond, target, source, reflow_target, _index in self._iter_reflow_batch_samples(batch)
        ]
        return self._mean_metrics(metrics)
